# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'Install npm'
  inputs:
    command: 'install'
    workingDir: 'app'
- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    workingDir: 'app'
    customCommand: 'run build'
    verbose: true
    
- task: PublishBuildArtifacts@1
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/app/build'
    artifact: 'drop'
    publishLocation: 'pipeline'
    
