version: "3.5"

services:
  ####################### Database #######################
  database:
    container_name: ce-database
    restart: on-failure:1
    build:
      context: api/db/mssql
    env_file:
      - api/db/mssql/.env
    ports:
      - ${DATABASE_PORT:-51433}:1433
    volumes:
      - database:/var/opt/mssql
    networks:
      - coevent

  ####################### API #######################
  api:
    container_name: ce-api
    depends_on:
      - database
    restart: on-failure:1
    build:
      context: api
      args:
        BUILD_CONFIGURATION: Debug
    env_file: api/src/.env
    ports:
      - ${API_HTTP_PORT:-50081}:80
      - ${DAPI_HTTPS_PORT:-50444}:443
    volumes:
      - "./api/certs:/root/https"
    networks:
      - coevent

  ####################### APP #######################
  app:
    container_name: ce-app
    depends_on:
      - api
    restart: on-failure:1
    stdin_open: true
    tty: true
    build:
      context: app
    env_file: ./app/.env.development
    volumes:
      - ./app/src:/usr/app/src
      - ./app/public:/usr/app/public
      - app-node-cache:/usr/app/node_modules
    ports:
      - ${APP_HTTP_PORT:-50080}:3000
      - ${APP_HTTPS_PORT:-50443}:3000
    networks:
      - coevent

####################### Networks Definition #######################
networks:
  coevent:
    name: coevent
    driver: bridge

####################### Volumes Definition #######################
volumes:
  database:
    name: ce-database
  app-node-cache:
    name: ce-app-node-cache
